name: flutter_template
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # config
  flutter_native_splash: ^2.4.2 # for adding native splash screen

  # network
  dio: ^5.7.0 # for adding interceptors, cancelling requests

  # performance
  flutter_displaymode: ^0.6.0 # for setting resolution and refresh rate for android only

  # assets
  image_cropper: ^8.0.2 # for cropping images
  image_gallery_saver: ^2.0.3 # for saving image to gallery after picking
  image_picker: ^1.1.2 # for picking images
  cached_network_image: ^3.4.1 # for caching images
  flutter_image_compress: ^2.3.0 # for compressing images
  flutter_svg: ^2.0.10+1 # for svg support

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
